server:
  port: "8080"
  shutdown_timeout: 10s
  hide_banner: true
  hide_port: true
postgres:
  db_user: ${POSTGRES_DB_USER}
  db_password: ${POSTGRES_DB_PASSWORD}
  db_name: ${POSTGRES_DB_NAME}
  db_host: localhost
  db_port: "5432"
jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  refresh_secret: ${JWT_REFRESH_SECRET}
  access_token_ttl: 1h
  refresh_token_ttl: 4h # update redis ttl accordingly always add buffer with this as base
redis:
  address: localhost:6379
  password: ${REDIS_PASSWORD}
  db: 0
  prefix: "iot-redis-jti:"
  ttl: 4h15m  # related to refresh_token_ttl -> ttl = refresh_token_ttl + buffer
auth:
  default_new_user_role_slug: "viewer"
  request_reset_password_token_ttl: 30m
frontend:
  base_url: ${FRONTEND_BASE_URL}



