schema:
  - # sensor-temp-001 entry
    sensor_code: "sensor-temp-001"
    schema_version: 1 # Integer version, matches DTO and config struct
    fields: # This is a list of SensorField objects
      - code: 1 # First field object
        name: "temperature"
        unit: "°C"
        data_type: "float"
      - code: 2 # Second field object
        name: "humidity"
        unit: "%"
        data_type: "float"

  - # sensor-env-002 entry
    sensor_code: "sensor-env-002"
    schema_version: 1
    fields: # This is a list of SensorField objects
      - code: 1
        name: "co2_level"
        unit: "ppm"
        data_type: "int"
      - code: 2
        name: "air_quality_index"
        unit: "AQI"
        data_type: "int"
      - code: 3
        name: "vibration"
        unit: "m/s²"
        data_type: "float"

  - # sensor-motion-003 entry
    sensor_code: "sensor-motion-003"
    schema_version: 1
    fields: # This is a list of SensorField objects
      - code: 1
        name: "acceleration_x"
        unit: "m/s²"
        data_type: "float"
      - code: 2
        name: "acceleration_y"
        unit: "m/s²"
        data_type: "float"
      - code: 3
        name: "acceleration_z"
        unit: "m/s²"
        data_type: "float"
      - code: 4
        name: "gyroscope_x"
        unit: "°/s"
        data_type: "float"
      - code: 5
        name: "gyroscope_y"
        unit: "°/s"
        data_type: "float"
      - code: 6
        name: "gyroscope_z"
        unit: "°/s"
        data_type: "float"

  - # sensor-gps-004 entry
    sensor_code: "sensor-gps-004"
    schema_version: 1
    fields: # This is a list of SensorField objects
      - code: 1
        name: "latitude"
        unit: "°"
        data_type: "float"
      - code: 2
        name: "longitude"
        unit: "°"
        data_type: "float"
      - code: 3
        name: "altitude"
        unit: "m"
        data_type: "float"
      - code: 4
        name: "speed"
        unit: "km/h"
        data_type: "float"
      - code: 5
        name: "direction"
        unit: "°"
        data_type: "float"

  - # sensor-energy-005 entry
    sensor_code: "sensor-energy-005"
    schema_version: 1
    fields: # This is a list of SensorField objects
      - code: 1
        name: "voltage"
        unit: "V"
        data_type: "float"
      - code: 2
        name: "current"
        unit: "A"
        data_type: "float"
      - code: 3
        name: "power"
        unit: "W"
        data_type: "float"
      - code: 4
        name: "energy_consumed"
        unit: "kWh"
        data_type: "float"